#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/RunFunctions      # Tutorial run functions
#------------------------------------------------------------------------------
# current angle of attack
alpha=0.000000

# check if already been meshed, e.g. when re-starting simulation from previous time step we need to avoid this step
if [ ! -d "constant/polyMesh" ]; then
    # execute meshing
    ./Allrun.pre
    cp -r 0.orig 0
else
  echo "Meshing already executed. To re-run the meshing step execute the Allclean script."
fi

# decompose and renumber
runApplication decomposePar
runParallel renumberMesh -overwrite

# initialize
runParallel potentialFoam -writephi

# execute flow solver
runParallel "$(getApplication)"

latestTime=$(foamListTimes -case processor0 | tail -1)

# rename the postProcessing directories according to the current AoA
mv "postProcessing/forces/0" "postProcessing/forces/alpha_${alpha}"
mv "postProcessing/solverInfo/0" "postProcessing/solverInfo/alpha_${alpha}"
mv "postProcessing/yPlus/0" "postProcessing/yPlus/alpha_${alpha}"
mv "postProcessing/wallShearStress/0" "postProcessing/wallShearStress/alpha_${alpha}"
mv "postProcessing/surface/${latestTime}" "postProcessing/surface/alpha_${alpha}"
foamListTimes -case postProcessing/surface/ | while read time; do rm -rf "postProcessing/surface/$time"; done

# reconstruct the latest time
# runApplication reconstructPar -latestTime

