#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/RunFunctions      # Tutorial run functions
#------------------------------------------------------------------------------
latestTime=$(foamListTimes -case processor0 | tail -1)

# remove everything not required for the next AoA
rm -r log.* processor* 0

cp -r 0.orig 0

# now modify the A0A within U
# runApplication mapFields -consistent -sourceTime 'latestTime' .

# rm -r "${latestTime}"
